version: '3'
services:
  db:
    container_name: pagemill-db
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
    restart: unless-stopped
  web:
    container_name: pagemill-web
    build: .
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
    volumes:
      - ./pagemill:/home/docker/pagemill
      - ./pagemill/log:/var/log/pagemill
      - /var/run
    ports:
      - "8000:8000"
      - "1338:22"
    depends_on:
      - db
    command: /bin/bash init-web
    restart: unless-stopped
  nginx:
    container_name: pagemill-nginx
    image: nginx:1.26
    volumes_from:
      - web
    volumes:
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
  
