version: '3'
services:
  web:
    container_name: pagemill-web
    build: .
    volumes:
      - ./pagemill/log:/var/log/pagemill
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: /home/docker/docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
  
