#!/usr/bin/env bash

sed 's/FQDN_OR_IP/'${FQDN_OR_IP}'/g' $NGINX_DIR/$NGINX_CONF_FILE > $NGINX_DIR/nginx.conf
if [[ $USE_SSL = 'true' ]]; then
    sed -i 's/SSL_CERT_FILE/'${SSL_CERT_FILE}'/g' $NGINX_DIR/nginx.conf
    sed -i 's/SSL_KEY_FILE/'${SSL_KEY_FILE}'/g' $NGINX_DIR/nginx.conf
fi

docker exec -ti pagemill-nginx cp /home/docker/pagemill/nginx/nginx.conf /etc/nginx/conf.d/default.conf
docker exec -ti pagemill-nginx nginx -s reload

exit 0;